#!/bin/zsh
##? os - Start the Overmind process manager with the appropriate Procfile.
##?
##? Uses Procfile.andrew when one exists in the current directory, else Procfile.dev.
##?
##? Usage: os [flags]

if [[ -f Procfile.andrew ]]; then
  overmind start "$@" -f Procfile.andrew -D -p 3000 -P 1
else
  overmind start "$@" -f Procfile.dev -D -p 3000 -P 1
fi
